# Generated by Django 4.1.13 on 2024-07-30 15:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('main_image', models.ImageField(default='default_images/default_camera_icon.png', upload_to='post_images')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(default=api.models.generate_object_id, max_length=24, primary_key=True, serialize=False)),
                ('image', models.ImageField(default=None, upload_to='post_images')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image_url', models.CharField(default='https://musicchallenge.s3.amazonaws.com/default_images/default_camera_icon.png', max_length=600)),
                ('name', models.CharField(default='default_camera_icon.png', max_length=100)),
            ],
        ),
    ]
