# Generated by Django 4.1.13 on 2024-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_album_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='main_image',
            field=models.ImageField(default='default_images/default_camera_icon.png', upload_to='post_images'),
        ),
    ]
