# Generated by Django 4.1.13 on 2024-07-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
