# Generated by Django 4.1.13 on 2024-07-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_image_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.CharField(default='/default_images/default_camera_icon.png', max_length=600),
        ),
    ]
