version: "3.9"
services:
  music-challenge:
    build: .
    container_name: music_challenge_frontend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - .:/usr/src/app      # Add this in order to rebuild the frontend container every time the frontend code changes (remove when deployed)
    environment:
      FLASK_ENV: development
    networks:
      - appnetwork
  redis:
    image: "redis:alpine"
    networks:
      - appnetwork

networks:
  appnetwork:
    external: true