name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Ensure this matches your project Python version

    - name: List current working directory
      run: |
        pwd
        ls -la
        cd src

        pwd
        ls -la
        cd backend
        
        pwd
        ls -la
        cd backend

        pwd
        ls -la
        cd backend

        pwd
        ls -la

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/backend/requirements.txt
    
    - name: Debug Secrets
      run: |
        echo "DB_NAME: $DB_NAME"
        echo "DB_HOST: $DB_HOST"
        echo "DB_USERNAME: $DB_USERNAME"
        echo "DB_PASSWORD: $DB_PASSWORD"
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    
    - name: Run migrations
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        echo "Running migrations..."
        python src/backend/backend/manage.py migrate

    - name: Deploy to production
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        echo "Deploying application..."
        # Add your deployment commands here, e.g., python manage.py runserver
        # python src/backend/backend/manage.py runserver
        cd src/backend/backend
        gunicorn --bind 0.0.0.0:8000 backend.wsgi:application --daemon
